### ISSUE TITLE
Unzip failure with v1.0.15

### ISSUE THREAD

**Issue by AdamAH** [shawnliujw/puppeteer-lambda#18]
Hi,

We've been running v1.0.14 with no problems. We just updated to v1.0.15 and now its failing on invocation with:
```
Error: invalid signature: 0x88b1f\n at /var/task/node_modules/unzip/lib/parse.js:59:13\n at runCallback (timers.js:794:20)\n at tryOnImmediate (timers.js:752:5)\n at processImmediate [as _immediateCallback] (timers.js:729:5)
```

Any ideas why? Seems like its related to unzipping the browser zip file maybe? Its the same file we've been using since v1.0.13

**Comment by shawnliujw** [comment]
@AdamAH   there is no changes , can you double check the exactly version of  unzip ?
here is the version in package.json `"unzip": "^0.1.11"` , the mini version maybe different
also please have a look https://github.com/EvanOxfeld/node-unzip/issues/89

**Comment by shawnliujw** [comment]
use `unzipper` instead of `unzip` to fix this problem
