### ISSUE TITLE
puppeteer-core

### ISSUE THREAD

**Issue by chesterm8** [shawnliujw/puppeteer-lambda#19]
Suggestion: Update to use puppeteer core rather than puppeteer; you wont need to get people to define PUPPETEER_SKIP_CHROMIUM_DOWNLOAD. 

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core

**Comment by shawnliujw** [comment]
thanks for your suggestion, it's done.
