### ISSUE TITLE
Failed to install puppeteer-lambda on mac

### ISSUE THREAD

**Issue by zhaoyi0113** [shawnliujw/puppeteer-lambda#20]
I followed the instruction on readme to install this dependency but it strucks on download. I run this command on Mac. Node is `v8.9.0` npm is `5.6.0`. Below is the output. I wonder whether I need to set the env `CUSTOM_CHROME=true` on local command or set it in lambda function? 

```
$CUSTOM_CHROME=true npm install puppeteer-lambda
> puppeteer-core@1.16.0 install /Users/joeyzhao/dev/bigcrunch/TheBigCrunch/TheLambda/lambdas/node_modules/puppeteer-core
> node install.js


> puppeteer-lambda@1.0.16 install /Users/joeyzhao/dev/bigcrunch/TheBigCrunch/TheLambda/lambdas/node_modules/puppeteer-lambda
> node src/install.js

downloading chrome ...
```

**Comment by shawnliujw** [comment]
@zhaoyi0113  you don't need `CUSTOM_CHROME` in your localhost and i just update , please use latest version `1.1.0` .   add `--registry=https://registry.npm.taobao.org/` if you still can't download  chromnium

**Comment by zhaoyi0113** [comment]
it works, thanks
