### ISSUE TITLE
Is there a way to make this library work in Mac?

### ISSUE THREAD

**Issue by zhaoyi0113** [shawnliujw/puppeteer-lambda#22]
I am using `puppeteer-lambda` on a Mac but I found it is hard to use this library. I get permission error about `/tmp` directory `Error: EACCES: permission denied, unlink '/tmp'`. And where can I find headless chrome for Mac?  I searched this project https://github.com/adieuadieu/serverless-chrome/releases but it doesn't have Mac version.

**Comment by shawnliujw** [comment]
If you wanna run it from your localhost, just install the module without any extra config, do not add  CUSTOM_CHROME = true. Just  npm install puppeteer-lambda, it depend on puppeteer, it will download the chromnium for u automatically

**Comment by zhaoyi0113** [comment]
That means I need to run `npm i` with `CUSTOM_CHROME = true` to deploy to lambda and run `npm i` without it for local?

**Comment by zhaoyi0113** [comment]
I have tried that but I get `Error: EACCES: permission denied, unlink '/tmp'` error. It seems that it tries to download it to `/tmp` directory which it doesn't have permission. Is there a way to configure the directory?

**Comment by shawnliujw** [comment]
Wired, it should download to the folder node_modules/puppeteer

**Comment by zhaoyi0113** [comment]
https://github.com/shawnliujw/puppeteer-lambda/blob/c642f61385185611d7ddcf8462537352d230adcf/src/config.js#L19

looks like the path can not be configured.

**Comment by shawnliujw** [comment]
but if you run from your localhost , without env `CUSTOM_CHROME=true` or ``  , it doesn't need to call these code to setup chrome , it will use chromnium from `puppeteer` .  you should see these from your console when u run `npm i puppeteer-lambda -d` :
`> puppeteer@1.16.0 install  <Your Project Folder>/node_modules/puppeteer
> node install.js

Downloading Chromium r656675 - 87.4 Mb [====================] 100% 0.0s
Chromium downloaded to  <Your Project Folder>/node_modules/puppeteer/.local-chromium/mac-656675`

**Comment by zhaoyi0113** [comment]
I listed `puppeteer-lambda` in my package.json, but `npm install` doesn't download the chrome. I got this error at runtime `Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"`.


```
"dependencies": {
    "aws-sdk": "^2.456.0",
    "body-parser": "^1.19.0",
    "download": "^7.1.0",
    "express": "^4.17.0",
    "puppeteer-lambda": "^1.0.16",
    "uuid": "^3.3.2"
  }
```

**Comment by shawnliujw** [comment]
Did u set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true before run npm install? If so, do noy do that, please follow the instruction

**Comment by zhaoyi0113** [comment]
I didn't set `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true`. What I found is the chrome is not downloaded when I run `npm install`. However it starts downloading when I run `npm install puppeteer-lambda`. Is there any different between these two commands? The first one is to install the dependencies based on `package.json`.

**Comment by shawnliujw** [comment]
Please use the latest version 1.1.0

**Comment by zhaoyi0113** [comment]
1.1.0 works as expected. Thanks for that.
