### ISSUE TITLE
error during run

### ISSUE THREAD

**Issue by liorg2** [shawnliujw/puppeteer-lambda#24]
when I run on lambda I get the following error:

/tmp/headless-chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

at onClose (/var/task/node_modules/puppeteer/lib/Launcher.js:342:14)
at Interface.helper.addEventListener (/var/task/node_modules/puppeteer/lib/Launcher.js:331:50)
at Interface.emit (events.js:194:15)
at Interface.EventEmitter.emit (domain.js:441:20)
at Interface.close (readline.js:379:8)
at Socket.onend (readline.js:157:10)
at Socket.emit (events.js:194:15)
at Socket.EventEmitter.emit (domain.js:441:20)
at endReadableNT (_stream_readable.js:1125:12)
at process._tickCallback (internal/process/next_tick.js:63:19) Failed to launch chrome!
/tmp/headless-chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

![image](https://user-images.githubusercontent.com/1691647/59615703-a8048300-912b-11e9-9d86-e39738963fa0.png)

**Comment by shawnliujw** [comment]
just confirmed , now the complied chromeless binary https://github.com/adieuadieu/serverless-chrome/releases  doesn't support  AWS lambda node 10.x , please use  the version `nodejs8.10`

**Comment by liorg2** [comment]
thanks a lot for replying .  For anyone that will face the same issue  as mine,  trying to work with google lighthouse 5 and puppeteer-lambda: Lighthouse requires Node 10 LTS (10.13) or later.

**Comment by shawnliujw** [comment]
You can have a try to build the chromium , i will also give a try

**Comment by liorg2** [comment]
If you send me a guide I can do it

**Comment by shawnliujw** [comment]
I have updated the readme file, u can find from there

**Comment by johnbalvin** [comment]
> just confirmed , now the complied chromeless binary https://github.com/adieuadieu/serverless-chrome/releases doesn't support AWS lambda node 10.x , please use the version `nodejs8.10`
Aws does not support 8.x version anymore

![image](https://user-images.githubusercontent.com/25888114/77018040-2061d400-694a-11ea-9f4c-2bcc9a13965e.png)

**Comment by hansooms999** [comment]
The issue was fixed for me when I changed my node.js runtime from 14.x to 12.x

**Comment by ghost** [comment]
If you want to use 14.x you can download working Chromium binaries (packaged as a layer) [here](http://chromiumforlambda.com).
