### ISSUE TITLE
 libnss3.so

### ISSUE THREAD

**Issue by johnbalvin** [shawnliujw/puppeteer-lambda#33]
#24 same error, solution was to use node 8.x but aws does not allow that version anymore 

![image](https://user-images.githubusercontent.com/25888114/77020756-c7e30480-6952-11ea-8cbe-5d6e4f96d274.png)

**Comment by shawnliujw** [comment]
@johnbalvin  sorry , i may not have time to fix this recently , please have a look https://github.com/alixaxel/chrome-aws-lambda  , should be able to help u . thanks

**Comment by ghost** [comment]
@johnbalvin Or take a look [here](http://chromiumforlambda.com).
